name: Deploy Cluster Monitoring
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      cluster:
        description: "The host to run the playbook on"
        required: false
        type: string
      tags:
        description: "The tags to run"
        required: false
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      cluster:
        description: "The host to run the playbook on"
        type: choice
        options:
          - test-k3s
          - game-k3s
          - all
      tags:
        description: "The tags to run"
        type: choice
        options:
          - all
          - node-exporter
          - prometheus
          - loki
          - grafana
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/deploy-monitoring.yml
      - roles/node-exporter/**
      - roles/prometheus/**
      - roles/loki/**
      - roles/grafana/**
      - deploy-monitoring.yml
      - inventory/hosts.yml
      - group_vars/**
      - host_vars/**

jobs:
  # TODO: move node exporter to ansible-homelab repository
  node-exporter:
    if: ${{ contains(fromJSON('["all", "node-exporter", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-monitoring.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: node-exporter
          vars: ""
  prometheus:
    if: ${{ !failure() && contains(fromJSON('["all", "prometheus", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-monitoring.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: prometheus
          vars: ""
  loki:
    if: ${{ !failure() && contains(fromJSON('["all", "loki", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-monitoring.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: loki
          vars: ""
  grafana:
    needs:
      - loki
      - prometheus
    if: ${{ !failure() && contains(fromJSON('["all", "grafana", ""]'), github.event.inputs.tags) && github.event.inputs.cluster == 'game-k3s' }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-monitoring.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: grafana
          vars: ""
