name: Deploy Full Cluster
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: false
        type: choice
        options:
          - test-k3s
          - game-k3s
          - all
  pull_request:
    branches:
      - main

jobs:
  ###
  ### RESET TEST CLUSTER BEFORE DEPLOYING
  ###
  reset-test-cluster:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/reset-cluster.yml
    with:
      host: test-k3s
    secrets: inherit

  deploy-nodes:
    needs:
      - reset-test-cluster
    if: ${{ !failure() }}
    uses: ./.github/workflows/deploy-nodes.yml
    with:
      cluster: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
    secrets: inherit

  deploy-middleware:
    needs:
      - deploy-nodes
    if: ${{ !failure() }}
    uses: ./.github/workflows/deploy-middleware.yml
    with:
      cluster: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
    secrets: inherit

  deploy-monitoring:
    needs:
      - deploy-nodes
      - deploy-middleware
    if: ${{ !failure() }}
    uses: ./.github/workflows/deploy-monitoring.yml
    with:
      cluster: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
    secrets: inherit
