name: Deploy Cluster Nodes
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: true
        type: string
      tags:
        description: "The tags to run"
        required: false
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: true
        type: choice
        options:
          - proxy-k3s
          - proxy-k3s
          - game-k3s
          - all
      tags:
        description: "The tags to run"
        required: true
        type: choice
        options:
          - all
          - agent
          - cluster-config
          - haproxy
          - helm
          - init-managers
          - init-workers
          - prereq
          - server
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/deploy-nodes.yml
      - roles/k3s-server/**
      - roles/k3s-agent/**
      - roles/k3s-prereq/**
      - roles/haproxy/**
      - roles/helm/**
      - deploy-nodes.yml
      - inventory/hosts.yml
      - group_vars/**
      - host_vars/**

jobs:
  ###
  ### CLUSTER SETUP
  ###
  haproxy:
    if: ${{ contains(fromJSON('["all", "haproxy", "server", "agent", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'proxy-k3s' }}
          tags: haproxy
          vars: ""

  prereq:
    needs:
      - haproxy
    if: ${{ !failure() && contains(fromJSON('["all", "prereq", "server", "agent", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'proxy-k3s' }}
          tags: prereq
          vars: ""

  servers:
    needs:
      - prereq
    if: ${{ !failure() && contains(fromJSON('["all", "server", "init-managers", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'proxy-k3s' }}
          tags: init-managers
          vars: ""

  workers:
    needs:
      - servers
    if: ${{ !failure() && contains(fromJSON('["all", "agent", "init-workers", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'proxy-k3s' }}
          tags: init-workers
          vars: ""

  helm:
    needs:
      - prereq
    if: ${{ !failure() && contains(fromJSON('["all", "helm", "server", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'proxy-k3s' }}
          tags: helm
          vars: ""

  cluster-config:
    needs:
      - servers
      - workers
    if: ${{ !failure() && contains(fromJSON('["all", "cluster-config", "server", "agent", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'proxy-k3s' }}
          tags: cluster-config
          vars: ""
