name: Deploy Cluster Middleware
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: true
        type: string
      tags:
        description: "The tags to run"
        required: false
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: true
        type: choice
        options:
          - test-k3s
          - game-k3s
          - all
      tags:
        description: "The tags to run"
        type: choice
        options:
          - all
          - cert-manager
          - cilium
          - longhorn
          - metallb
          - pihole
          - traefik
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/deploy-middleware.yml
      - roles/cilium/**
      - roles/metallb/**
      - roles/longhorn/**
      - roles/cert-manager/**
      - roles/traefik/**
      - roles/pihole/**
      - deploy-middleware.yml
      - inventory/hosts.yml
      - group_vars/**
      - host_vars/**

jobs:
  cilium:
    if: ${{ contains(fromJSON('["all", "cilium", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: cilium
          vars: ""

  metallb:
    needs:
      - cilium
    if: ${{ !failure() && contains(fromJSON('["all", "metallb", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: metallb
          vars: ""

  longhorn:
    needs:
      - cilium
    if: ${{ !failure() && contains(fromJSON('["all", "longhorn", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: longhorn
          vars: ""

  cert-manager:
    needs:
      - longhorn
    if: ${{ !failure() && contains(fromJSON('["all", "cert-manager", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: cert-manager
          vars: ""

  traefik:
    needs:
      - metallb
      - longhorn
      - cert-manager
    if: ${{ !failure() && contains(fromJSON('["all", "traefik", ""]'), github.event.inputs.tags) }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: traefik
          vars: ""

  pihole:
    needs:
      - longhorn
      - metallb
    if: ${{ !failure() && contains(fromJSON('["all", "pihole", ""]'), github.event.inputs.tags) && github.event.inputs.cluster == 'game-k3s' }}
    runs-on:
      group: ansible
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: pihole
          vars: ""
