name: Join Cluster Node
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      node:
        description: "The node to run the playbook against"
        required: true
        type: string
        default: "test-k3s"
      tags:
        description: "The tags to run"
        required: false
        default: ""
      extra_vars:
        description: "Extra vars to pass to the playbook"
        required: false
        default: ""

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.node }}
          tags: ${{ github.event.inputs.tags }}
          vars: ${{ github.event.inputs.extra_vars }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-helm.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.node }}
          tags: ${{ github.event.inputs.tags }}
          vars: ${{ github.event.inputs.extra_vars }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: k3s-middleware.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.node }}
          tags: ${{ github.event.inputs.tags }}
          vars: ${{ github.event.inputs.extra_vars }}
