name: Patch Cluster Nodes
permissions:
  contents: read

on:
  schedule:
    # Run at 12:00 PM UTC every day
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook on"
        type: choice
        options:
          - test-k3s
          - proxy-k3s
          - game-k3s
          - all
      tags:
        description: "The tags to run"
        required: false
        default: "no-downtime"
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/patch-cluster.yml
      - roles/k3s-patching/tasks/main.yml
      - patch-cluster.yml
      - inventory/hosts.yml
      - group_vars/**
      - host_vars/**

jobs:
  test-cluster:
    runs-on:
      group: ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: patch-cluster.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: ${{ github.event.inputs.tags != '' && github.event.inputs.tags || 'all' }}
          vars: ""

  proxy-cluster:
    runs-on:
      group: ansible
    needs:
      - test-cluster
    if: ${{ success() }}
    steps:
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: patch-cluster.yml
          inventory_path: inventory/hosts.yml
          hosts: "proxy-k3s"
          tags: ""
          vars: ""

  game-cluster:
    runs-on:
      group: ansible
    needs:
      - test-cluster
    if: ${{ success() && github.event.schedule == '0 12 * * 1' }}
    steps:
      - uses: espresso-software/actions/ansible/run-playbook@main
        # Only run downtime patches on game-k3s cluster on Mondays at 12:00 PM UTC
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: patch-cluster.yml
          inventory_path: inventory/hosts.yml
          hosts: "game-k3s"
          tags: "downtime"
          vars: ""
