name: Patch Cluster Nodes
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook on"
        required: false
        default: "all"
      tags:
        description: "The tags to run"
        required: false
        default: "no-downtime"
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/patch-cluster.yml
      - patch-cluster.yml
      - inventory/hosts.yml
      - group_vars/**
      - host_vars/**

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: patch-cluster.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: ${{ github.event.inputs.tags != '' && github.event.inputs.tags || 'no-downtime' }}
          vars: ""
