name: Reset Cluster [DESTRUCTIVE]
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: true
        type: choice
        options:
          - test-k3s
          # Uncomment the line below to enable reset for production clusters
          # - proxy-k3s
          # - game-k3s

jobs:
  deploy:
    runs-on:
      group: ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: reset-cluster.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: ""
          vars: ""
