name: Restart Nodes [DISRUPTIVE]
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook against"
        required: true
        type: choice
        options:
          - test-k3s
          - game-k3s
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/restart-nodes.yml
      - restart-nodes.yml

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: restart-nodes.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: ""
          vars: ""
