name: Upgrade k3s Version [DISRUPTIVE]

on:
  workflow_dispatch:
    inputs:
      host:
        description: "The host to run the playbook on"
        required: false
        default: "all"
      tags:
        description: "The tags to run"
        required: false
        default: "no-downtime"
      version:
        description: "The version to upgrade to"
        required: true
        default: "v1.32.0+k3s1"

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - name: Set extra_args
        id: set_extra_args
        run: |
          args_string=""
          if [ -n "${{ github.event.inputs.host }}" ]; then
            args_string="${args_string} -l ${{ github.event.inputs.host }}"
          fi
          if [ -n "${{ github.event.inputs.tags }}" ]; then
            args_string="${args_string} --tags ${{ github.event.inputs.tags }}"
          fi
          if [ -n "${{ github.event.inputs.version }}" ]; then
            args_string="${args_string} --extra-vars 'k3s_version=${{ github.event.inputs.version }}'"
          fi
          echo "::set-output name=extra_args::${args_string}"

      - name: Setup vault token
        run: |
          echo "${{ secrets.VAULT_DECRYPT_TOKEN }}" > /tmp/vault_pass

      - name: Run playbook
        run: |
          ansible-playbook -i inventory/hosts.ini -l ${{ github.event.inputs.host }} k3s-upgrade.yml -v --vault-password-file /tmp/vault_pass ${{ steps.set_extra_args.outputs.extra_args }}

      - name: Remove vault pass
        if: always()
        run: |
          rm /tmp/vault_pass
