name: Upgrade k3s Version [DISRUPTIVE]
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "The cluster to run the playbook on"
        type: choice
        options:
          - test-k3s
          - game-k3s
      tags:
        description: "The tags to run"
        required: false
        default: "no-downtime"
      version:
        description: "The version to upgrade to"
        required: true
        default: "v1.32.0+k3s1"

jobs:
  deploy:
    runs-on:
      group: ansible

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.READ_ACCESS_TOKEN }}

      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: upgrade-cluster.yml
          inventory_path: inventory/hosts.yml
          hosts: ${{ github.event.inputs.cluster != '' && github.event.inputs.cluster || 'test-k3s' }}
          tags: ${{ github.event.inputs.tags != '' && github.event.inputs.tags || 'no-downtime' }}
          vars: |
            k3s_version: "${{ github.event.inputs.version }}"
